#HTTP Listener Config
http.internal.host=0.0.0.0
http.internal.port=8081

#HTTP Request Config
http.host=0.0.0.0
http.port=8082
responseTimeout=60000
responseTimeoutOCR=30000

#OCR Config
ocr.space.api.key=K83401522188957

#DB Config
db.host=127.0.0.1
db.port=3306
db.user=root
db.password=password
db.databaseName=banking_kyc